# Check the code with flake8 and if successful, run set up postgres database and run tests.

name: Check and Test

on:
  pull_request:
    branches: ["main", "release/*", "hotfix/*"]

permissions:
  contents: read

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    container: python:3.11.7-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.lock
        shell: bash

      - name: Check with flake8
        run: |
          flake8 ./src
          vulture ./src

      - name: Test with pytest
        run: |
          pytest -x --cov=./src/pss_fleet_data --cov-report xml:cov.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./cov.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true